name: development
channels:
  - conda-forge
  - defaults

dependencies:
    # Base depends
  - python>=3.8
  - pip
  - numpy
  - pandas
  - geopandas
  - pygeos
  - scikit-learn

    # graph
  - scipy
  - networkx
  - pandana
  
    # development
  - ipykernel

    # Testing
  - black
  - pytest
  - pytest-cov
  - codecov

    # Pip-only installs
  #- pip:
  #  - codecov

