name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - pandas
  - geopandas
  - pygeos
  - scipy
  - sklearn
  - networkx
  - pandana


    # Pip-only installs
  #- pip:

