name: docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python>=3.8
  - pip
  - numpy
  - pandas
  - geopandas
  - pygeos
  - scipy
  - scikit-learn
  - networkx
  - pandana


    # Pip-only installs
  #- pip:

